apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls
  namespace: nextcloud
spec:
  secretName: nextcloud-tls
  dnsNames:
    - nextcloud.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
