apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: ClusterIP
  admin_user: $(AWX_ADMIN_USER)
  admin_password_secret: awx-admin
  postgres_configuration_secret: ""
  ingress_type: ingress
  ingress_tls_secret: awx-tls
  hostname: $(AWX_HOST)
  replicas: 1
  web_replicas: 1
  task_replicas: 1
<<<<<<< HEAD:k8s/addons/awx-operator/awx.yaml
  ee_default_image: quay.io/ansible/awx-ee:latest
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin
  namespace: awx
type: Opaque
stringData:
  password: $(AWX_ADMIN_PASSWORD)
=======
  ee_default_image: quay.io/ansible/awx-ee:26.2.1
>>>>>>> b42d7de (Refine AWX admin secret handling):awx/awx-small.yaml
