apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: awx-operator
  namespace: flux-system
spec:
  interval: 30m
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: awx-operator
    namespace: flux-system
  targetNamespace: awx
  wait: false
