apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: flux-system
spec:
  interval: 15m
  releaseName: awx-operator
  targetNamespace: awx
  install:
    createNamespace: true
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: uninstall
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: uninstall
  chart:
    spec:
      chart: awx-operator
      version: "2.19.1"
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: flux-system
  values:
    watchNamespace: awx
