apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-django-media
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  hostPath:
    path: /srv/apps/django-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-django-media
  namespace: django
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
  volumeName: pv-django-media
