apiVersion: v1
kind: PersistentVolume
metadata:
  name: labz-jellyfin-media-pv
  labels:
    pv-role: jellyfin-media
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: ${LABZ_MOUNT_MEDIA}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Ti
  selector:
    matchLabels:
      pv-role: jellyfin-media
