apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minecraft
spec:
  capacity:
    storage: 60Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  hostPath:
    path: /srv/minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minecraft
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: local-hostpath
  volumeName: pv-minecraft
