apiVersion: v1
kind: PersistentVolume
metadata:
  name: labz-nextcloud-pv
  labels:
    pv-role: nextcloud-data
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: ${NEXTCLOUD_DATA_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    pv-role: nextcloud-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      pv-role: nextcloud-data
