apiVersion: v1
kind: PersistentVolume
metadata:
  name: labz-postgresql-pv
  labels:
    pv-role: postgresql-data
spec:
  capacity:
    storage: ${PG_STORAGE_SIZE}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: ${POSTGRES_DATA_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: ${PG_STORAGE_SIZE}
  selector:
    matchLabels:
      pv-role: postgresql-data
