apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitwarden
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
  - ../../../bitwarden/sops-secrets/bitwarden-env.sops.yaml
