repos:
  - repo: local
    hooks:
      - id: docs-build
        name: Build MkDocs documentation
        entry: make docs
        language: system
        pass_filenames: false
        stages: [commit]
        files: ^(docs/|mkdocs\.yml|Makefile)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
