---
extends: default

rules:
  line-length:
    max: 140
    level: warning
  document-start:
    present: false
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false
