apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 15m
  releaseName: pihole
  targetNamespace: pihole
  dependsOn:
    - name: metallb
      namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: uninstall
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: uninstall
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: pihole-helm-values
      valuesKey: values.yaml
