apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: django-cert
  namespace: django
spec:
  secretName: django-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - django.home.arpa
