apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: metallb
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
  releaseName: traefik-ingress
  targetNamespace: traefik-system
  install:
    createNamespace: true
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: uninstall
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: uninstall
  chart:
    spec:
      chart: traefik
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
