apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: ">=22.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.88.201
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirected: true
      websecure:
        tls:
          enabled: true
