apiVersion: ENC[AES256_GCM,data:k6E=,iv:jT9TJ/SwyFK6pP6LPvv4Aqy9pkO793l9Dapq9VMWhNg=,tag:wzvMtEj2Vms+OAxJb9QXGA==,type:str]
kind: ENC[AES256_GCM,data:D9YOjBc7,iv:9c28RRWuvHC21SQc8kjUJP6wuNQ5Gj5lvNF4sM4LHzQ=,tag:tT1x+quEMT9QIFZhpWXcyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7SJUqd7tcItkz9JzB8KfNvDa,iv:n8vyO430ndhhtsPyt4MR0eNkSvNo1iI6OpzQcJIMems=,tag:qaA0Ktqn3kzEZoES393hgQ==,type:str]
    namespace: ENC[AES256_GCM,data:InR8ud6FrIVz,iv:TPzQcvJ4SjNYtKv2m1j9NF0dwGMCYhqlC6JWtVUSLZw=,tag:oAyNHBqYC+o8z2PjH3hl9Q==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:CpqKyiBjot0W,iv:w4z6rse8Ao6rq1HgCsPGwLMj56FmGLruaLaO1AmBXY0=,tag:B4ZkHM7LlF39j6583IJBhA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:UJshFtBvYSg=,iv:joLjlTVeBVRsDI1Er/ZaKGtL6JMhmPFxeon+HMoYd+c=,tag:osI5FtU5tdPJFyC5s2WDMw==,type:str]
        app.kubernetes.io/instance: ENC[AES256_GCM,data:X8c/9E+5/PW9,iv:AYh6oj2gr0nVg7cDqTnQVf+MTUghlBPnfu4+ZeIGedM=,tag:DWdxzRDS8t1sfstwaCizGA==,type:str]
    annotations:
        reloader.stakater.com/match: ENC[AES256_GCM,data:6F6BPA==,iv:BQiao50693s/IYd42v/C109eHV+Onpbhl4ex1gJFGaI=,tag:IqBilktoUpUYmdu7RcKyiw==,type:str]
type: ENC[AES256_GCM,data:B3zLoQVb,iv:8uyoP5HgbRZhbEXH4s2Sae2taKjiBTiwPz/J8W3FogI=,tag:R2Z5dJsF5wcWXcmBKOqqvg==,type:str]
stringData:
    dsn: ENC[AES256_GCM,data:02Cd/KnvIoQGIdCSdGOzeQJYXIGQSMrbmkfsChYnEhe8Z1Tc3CelzErnI4rtnfzrw87B5dH8E/kGTu9rPXs54GWMqm82Piw1u6W/5TMMsICILTR9xg==,iv:rbOu1QK9H2P6ooFdLK5BHyZFtyXRR2yN5uL4uwHxcAw=,tag:SxYcgCxK9V+DUYqUxde6Jw==,type:str]
    host: ENC[AES256_GCM,data:cz+yC4NIcKfG+43fZN8y7hYyq/GY3NZfATxwFoDI67TOB5udtWk=,iv:9mFBtBIyB9d3pj7Y7CXrZ1hMpUlE0zsqyFkZuI8BANI=,tag:wFzkmAYl4w5Kugtj8F94Ag==,type:str]
    port: ENC[AES256_GCM,data:5iTaFA==,iv:HGqT5Du4dF+etReNRL5RFlCu7TvGFfZ2ppwtjAfTaqA=,tag:aFDzl8wAmOLHV0i07rL50Q==,type:str]
    database: ENC[AES256_GCM,data:aPBLQ03x2Dql,iv:otNl036FJtyos5nuk0t3WOCrIFuv2owYj+zMdHFBjss=,tag:+2Fqo43byOUW2SeP44pMgw==,type:str]
    username: ENC[AES256_GCM,data:tJuIkB1VZVv/,iv:opSMTvi2ydtb4HMIEooaoTMYvcTEXNGA2ba7r99GjW4=,tag:p524apWoay2ySxEVcsJYCA==,type:str]
    password: ENC[AES256_GCM,data:tyE0nJYTgto=,iv:MA7ZXX1pe5WtkmMuPHnETL3ho6k5UEpCNBPgxx1SG2g=,tag:jqhf0/Xdm+5NFeHWdHW6Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kdhf2edf7xq9r23zmg9v26rp60fer7tu8xy4u3d2djjqtgt3psqteva54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRFcwbk05d0ZNNlAyWVNn
            Z3dRZVNyRzZvcnk3UVkvRzRUMVVRa1FXdXhjCkUrbUszRXR2Z0ZpZUtSQkxqTWp1
            anVlOWVCQjFYZFk2MHFKU3JsODUxY1UKLS0tIDR6bkVSMnZRaG5TTWFOb3ZiaDhK
            QldNaDZpcEtpeWpVcHNOeFRQYXp2VUUK2Hu07uWznofk/6VSUzFyY3EnVglDcjdE
            Tk81QHcmt1Khe4/nhdCrxWiOVAdtBhKdfRPZFLZSeqpeKQ0wjjEgfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T15:01:12Z"
    mac: ENC[AES256_GCM,data:GxxcXNtGF+VcToSt/UECgOxnjbY6opx+oBsmQZsjiZlwpFQzIr2TI585mDiWEZ4gFpzN/sAxhiB/iRh4+QQzkmiQfwb0Y0cF4GqWtBMIoK7d17VH2tfMIMICURdR/gUrTCv/Nm2gOc/maDThul77T45Ptg8eToeRe7c0wYgUnpc=,iv:NclZYXX3Fkv+fpMvGNQjjXl5DXmOP8cD/HestDuVXXc=,tag:CEMGsf6HpVXrsW2r41PG4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
