apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: labz-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: labz-internal-root
  secretName: labz-root-ca-secret
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: labz-ca-issuer
spec:
  ca:
    secretName: labz-root-ca-secret
