apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
spec:
  secretName: homepage-tls
  dnsNames:
    - home.lab-minikube.labz.home.arpa
  issuerRef:
    name: labz-ca-issuer
    kind: ClusterIssuer
