apiVersion: v1
kind: Service
metadata:
  name: mc
  namespace: minecraft
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.88.204
  selector:
    app: mc
  ports:
  - name: mc
    port: 25565
    targetPort: 25565
