apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: ClusterIP
  admin_user: ${AWX_ADMIN_USER}
  admin_password_secret: awx-admin
  postgres_configuration_secret: ""
  ingress_type: ingress
  ingress_tls_secret: awx-tls
  hostname: awx.lab-minikube.labz.home.arpa
  replicas: 1
  web_replicas: 1
  task_replicas: 1
  ee_default_image: quay.io/ansible/awx-ee:26.2.1
