apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: labz-apps-tls
spec:
  secretName: labz-apps-tls
  dnsNames:
    - media.labz.home.arpa
  issuerRef:
    name: labz-ca-issuer
    kind: ClusterIssuer
