logs:
  general:
    level: INFO
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.88.201
ingressRoute:
  dashboard:
    enabled: true
ports:
  web:
    redirected: true
  websecure:
    tls:
      enabled: true
