deployment:
  replicas: 1
ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
ingressClass:
  enabled: true
  isDefaultClass: true
logs:
  general:
    level: INFO
  access:
    enabled: true
service:
  annotations: {}
