apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../addons/metallb
  - ../addons/traefik
  - ../addons/cert-manager
  - ../addons/awx-operator
  - ../apps/pihole
  - ../apps/nextcloud
  - ../apps/jellyfin
  - ../apps/bitwarden
  - ../apps/homepage
