apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: observability
spec:
  secretName: grafana-tls
  dnsNames: ["$(GRAFANA_HOST)"]
  issuerRef: { name: labz-ca-issuer, kind: ClusterIssuer }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prom-cert
  namespace: observability
spec:
  secretName: prom-tls
  dnsNames: ["$(PROMETHEUS_HOST)"]
  issuerRef: { name: labz-ca-issuer, kind: ClusterIssuer }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alert-cert
  namespace: observability
spec:
  secretName: alert-tls
  dnsNames: ["$(ALERTMANAGER_HOST)"]
  issuerRef: { name: labz-ca-issuer, kind: ClusterIssuer }
