apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - release.yaml
  - ../../observability/certs.yaml
  - ../../observability/sops-secrets/grafana-admin.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - values.yaml=../../observability/kps-values.yaml
generatorOptions:
  disableNameSuffixHash: true
