apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  releaseName: kube-prometheus-stack
  targetNamespace: observability
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=58.0.0 <59.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - $(GRAFANA_HOST)
        tls:
          - secretName: grafana-tls
            hosts:
              - $(GRAFANA_HOST)
      adminPassword: admin
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - $(PROMETHEUS_HOST)
        tls:
          - secretName: prom-tls
            hosts:
              - $(PROMETHEUS_HOST)
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - $(ALERTMANAGER_HOST)
        tls:
          - secretName: alert-tls
            hosts:
              - $(ALERTMANAGER_HOST)
