apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 15m
  releaseName: kube-prometheus-stack
  targetNamespace: observability
  dependsOn:
    - name: traefik-ingress
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.6.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
      valuesKey: values.yaml
