name: CI

on:
  push:
    paths:
      - 'apps/**'
      - 'clusters/**'
      - 'data/**'
      - 'flux/**'
      - 'infra/**'
      - 'k8s/**'
      - 'observability/**'
      - '**/*.sh'
      - 'Makefile'
      - '.pre-commit-config.yaml'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'apps/**'
      - 'clusters/**'
      - 'data/**'
      - 'flux/**'
      - 'infra/**'
      - 'k8s/**'
      - 'observability/**'
      - '**/*.sh'
      - 'Makefile'
      - '.pre-commit-config.yaml'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install lint tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit==3.7.1

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test
