name: GitOps CI

on:
  push:
    paths:
      - 'apps/**'
      - 'clusters/**'
      - 'data/**'
      - 'flux/**'
      - 'infra/**'
      - 'k8s/**'
      - 'observability/**'
      - '**/*.sh'
      - '.github/workflows/gitops-ci.yml'
  pull_request:
    paths:
      - 'apps/**'
      - 'clusters/**'
      - 'data/**'
      - 'flux/**'
      - 'infra/**'
      - 'k8s/**'
      - 'observability/**'
      - '**/*.sh'
      - '.github/workflows/gitops-ci.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Static analysis (required)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: .pre-commit-config.yaml

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Run ShellCheck
        run: pre-commit run --all-files shellcheck

      - name: Run yamllint
        run: pre-commit run --all-files yamllint

      - name: Run kubeconform
        run: pre-commit run --all-files kubeconform

  validate:
    name: Validate GitOps Manifests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare local bin path
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Set up Flux CLI
        uses: fluxcd/flux2/action@v2
        with:
          version: '2.2.3'

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.3.0'

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Restore kubeconform cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/kubeconform
          key: kubeconform-${{ runner.os }}-0.6.3

      - name: Install kubeconform
        run: |
          set -euo pipefail
          KUBECONFORM_VERSION="0.6.3"
          CACHE_DIR="$HOME/.cache/kubeconform"
          CACHE_BIN="$CACHE_DIR/kubeconform-${KUBECONFORM_VERSION}"
          mkdir -p "$CACHE_DIR"
          if [ ! -x "$CACHE_BIN" ]; then
            tmpdir="$(mktemp -d)"
            curl -L "https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz" -o "$tmpdir/kubeconform.tar.gz"
            tar -xf "$tmpdir/kubeconform.tar.gz" -C "$tmpdir" kubeconform
            mv "$tmpdir/kubeconform" "$CACHE_BIN"
            rm -rf "$tmpdir"
          fi
          install -m 0755 "$CACHE_BIN" "$HOME/.local/bin/kubeconform"

      - name: Restore conftest cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/conftest
          key: conftest-${{ runner.os }}-0.52.1

      - name: Install Conftest
        run: |
          set -euo pipefail
          CONTFEST_VERSION="0.52.1"
          CACHE_DIR="$HOME/.cache/conftest"
          CACHE_BIN="$CACHE_DIR/conftest-${CONTFEST_VERSION}"
          mkdir -p "$CACHE_DIR"
          if [ ! -x "$CACHE_BIN" ]; then
            tmpdir="$(mktemp -d)"
            curl -L "https://github.com/open-policy-agent/conftest/releases/download/v${CONTFEST_VERSION}/conftest_${CONTFEST_VERSION}_Linux_x86_64.tar.gz" -o "$tmpdir/conftest.tar.gz"
            tar -xf "$tmpdir/conftest.tar.gz" -C "$tmpdir" conftest
            mv "$tmpdir/conftest" "$CACHE_BIN"
            rm -rf "$tmpdir"
          fi
          install -m 0755 "$CACHE_BIN" "$HOME/.local/bin/conftest"

      - name: Install Python dependencies
        run: |
          set -euo pipefail
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user pyyaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: gitops-ci

      - name: Install Flux CRDs in kind cluster
        run: |
          set -euo pipefail
          flux install --components-extra=image-reflector-controller,image-automation-controller --export | kubectl apply -f -
          kubectl wait --for=condition=Available --timeout=120s -n flux-system deployments --all

      - name: Render manifests with Kustomize
        run: |
          set -euo pipefail
          mkdir -p rendered-manifests/kustomize
          mapfile -t kustomizations < <(find clusters k8s -name kustomization.yaml -print | sort)
          if [ "${#kustomizations[@]}" -eq 0 ]; then
            echo "No kustomization.yaml files found"
            exit 1
          fi
          for kustomization in "${kustomizations[@]}"; do
            dir=$(dirname "$kustomization")
            rel=${dir#./}
            safe_name=$(echo "$rel" | tr '/._' '-' | tr '[:upper:]' '[:lower:]')
            echo "Building ${rel}"
            kustomize build "$dir" > "rendered-manifests/kustomize/${safe_name}.yaml"
          done

      - name: Build manifests with Flux
        run: |
          set -euo pipefail
          mkdir -p rendered-manifests/flux
          mapfile -t kustomizations < <(find clusters k8s -name kustomization.yaml -print | sort)
          if [ "${#kustomizations[@]}" -eq 0 ]; then
            echo "No kustomization.yaml files found for Flux build"
            exit 0
          fi
          for kustomization in "${kustomizations[@]}"; do
            dir=$(dirname "$kustomization")
            rel=${dir#./}
            safe_name=$(echo "$rel" | tr '/._' '-' | tr '[:upper:]' '[:lower:]')
            tmp_file=$(mktemp)
            printf '%s\n' \
              "apiVersion: kustomize.toolkit.fluxcd.io/v1" \
              "kind: Kustomization" \
              "metadata:" \
              "  name: ${safe_name}" \
              "  namespace: flux-system" \
              "spec:" \
              "  interval: 10m" \
              "  path: ./${rel}" \
              "  prune: false" \
              "  sourceRef:" \
              "    kind: GitRepository" \
              "    name: placeholder" >"$tmp_file"
            echo "Flux building ${rel}"
            flux build kustomization "${safe_name}" \
              --namespace=flux-system \
              --path=. \
              --kustomization-file="$tmp_file" \
              --dry-run > "rendered-manifests/flux/${safe_name}.yaml"
            rm -f "$tmp_file"
          done

      - name: Validate manifests with kubeconform
        run: |
          set -euo pipefail
          kubeconform -strict -ignore-missing-schemas -skip CustomResourceDefinition -summary rendered-manifests/kustomize/*.yaml

      - name: Server-side dry-run validation
        run: |
          set -euo pipefail
          python3 <<'PY'
import pathlib
import subprocess
import sys

import yaml

manifest_dir = pathlib.Path('rendered-manifests/kustomize')
failures = []
for manifest_file in sorted(manifest_dir.glob('*.yaml')):
    with manifest_file.open('r', encoding='utf-8') as fh:
        docs = list(yaml.safe_load_all(fh))
    for index, doc in enumerate(docs, start=1):
        if not doc:
            continue
        payload = yaml.safe_dump(doc, sort_keys=False).encode()
        proc = subprocess.run(
            ["kubectl", "apply", "--dry-run=server", "-f", "-"],
            input=payload,
            capture_output=True,
            check=False,
        )
        if proc.returncode != 0:
            stderr = proc.stderr.decode()
            if "no matches for kind" in stderr or "could not find the requested resource" in stderr:
                print(f"Skipping {manifest_file} document {index}: {stderr.strip()}")
                continue
            print(f"kubectl dry-run failed for {manifest_file} document {index}:\n{stderr}")
            failures.append((manifest_file, index, stderr))
if failures:
    sys.exit(1)
PY

      - name: Helm lint
        run: |
          set -euo pipefail
          mapfile -t charts < <(find . -name Chart.yaml -print | sort)
          if [ "${#charts[@]}" -eq 0 ]; then
            echo "No Helm charts found to lint"
            exit 0
          fi
          for chart_file in "${charts[@]}"; do
            chart_dir=$(dirname "$chart_file")
            echo "Linting Helm chart ${chart_dir}"
            helm lint "$chart_dir"
          done

      - name: Policy checks with Conftest
        run: |
          set -euo pipefail
          if [ -d policy ] || [ -d policies ]; then
            conftest test rendered-manifests/kustomize
          else
            echo "No policy directory found, skipping OPA/Conftest checks"
          fi

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered-manifests
          if-no-files-found: error
