name: GitOps CI

on:
  push:
    paths:
      - 'apps/**'
      - 'clusters/**'
      - 'data/**'
      - 'flux/**'
      - 'infra/**'
      - 'k8s/**'
      - 'observability/**'
      - '.github/workflows/gitops-ci.yml'
  pull_request:
    paths:
      - 'apps/**'
      - 'clusters/**'
      - 'data/**'
      - 'flux/**'
      - 'infra/**'
      - 'k8s/**'
      - 'observability/**'
      - '.github/workflows/gitops-ci.yml'
  workflow_dispatch:

permissions:
  contents: read

env:
  SHELLCHECK_VERSION: '0.10.0'
  KUBECONFORM_VERSION: '0.6.3'
  CONFTEST_VERSION: '0.52.1'
  TOOL_CACHE_DIR: ~/.cache/homelab-tooling

jobs:
  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare tool cache directories
        run: |
          set -euo pipefail
          mkdir -p "$TOOL_CACHE_DIR/shellcheck/bin"
          mkdir -p "$TOOL_CACHE_DIR/kubeconform/bin"
          echo "$TOOL_CACHE_DIR/shellcheck/bin" >> "$GITHUB_PATH"
          echo "$TOOL_CACHE_DIR/kubeconform/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Cache ShellCheck
        id: cache-shellcheck
        uses: actions/cache@v4
        with:
          path: ${{ env.TOOL_CACHE_DIR }}/shellcheck
          key: ${{ runner.os }}-shellcheck-${{ env.SHELLCHECK_VERSION }}

      - name: Install ShellCheck
        if: steps.cache-shellcheck.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -sSLo "${tmpdir}/shellcheck.tar.xz" "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"
          tar -xJf "${tmpdir}/shellcheck.tar.xz" -C "${tmpdir}"
          install -m 0755 "${tmpdir}/shellcheck-v${SHELLCHECK_VERSION}/shellcheck" "${TOOL_CACHE_DIR}/shellcheck/bin/shellcheck"
          rm -rf "${tmpdir}"

      - name: Cache kubeconform
        id: cache-kubeconform
        uses: actions/cache@v4
        with:
          path: ${{ env.TOOL_CACHE_DIR }}/kubeconform
          key: ${{ runner.os }}-kubeconform-${{ env.KUBECONFORM_VERSION }}

      - name: Install kubeconform
        if: steps.cache-kubeconform.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -sSLo "${tmpdir}/kubeconform.tar.gz" "https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz"
          tar -xzf "${tmpdir}/kubeconform.tar.gz" -C "${tmpdir}" kubeconform
          install -m 0755 "${tmpdir}/kubeconform" "${TOOL_CACHE_DIR}/kubeconform/bin/kubeconform"
          rm -rf "${tmpdir}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install yamllint
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          python -m pip install yamllint

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.3.0'

      - name: Run lint suite
        run: ./scripts/run-lint-suite.sh

  validate:
    name: Validate GitOps Manifests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare tool cache directories
        run: |
          set -euo pipefail
          mkdir -p "$TOOL_CACHE_DIR/kubeconform/bin"
          mkdir -p "$TOOL_CACHE_DIR/conftest/bin"
          echo "$TOOL_CACHE_DIR/kubeconform/bin" >> "$GITHUB_PATH"
          echo "$TOOL_CACHE_DIR/conftest/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Cache kubeconform
        id: cache-kubeconform-validate
        uses: actions/cache@v4
        with:
          path: ${{ env.TOOL_CACHE_DIR }}/kubeconform
          key: ${{ runner.os }}-kubeconform-${{ env.KUBECONFORM_VERSION }}

      - name: Install kubeconform
        if: steps.cache-kubeconform-validate.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -sSLo "${tmpdir}/kubeconform.tar.gz" "https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz"
          tar -xzf "${tmpdir}/kubeconform.tar.gz" -C "${tmpdir}" kubeconform
          install -m 0755 "${tmpdir}/kubeconform" "${TOOL_CACHE_DIR}/kubeconform/bin/kubeconform"
          rm -rf "${tmpdir}"

      - name: Cache Conftest
        id: cache-conftest
        uses: actions/cache@v4
        with:
          path: ${{ env.TOOL_CACHE_DIR }}/conftest
          key: ${{ runner.os }}-conftest-${{ env.CONFTEST_VERSION }}

      - name: Install Conftest
        if: steps.cache-conftest.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -sSLo "${tmpdir}/conftest.tar.gz" "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz"
          tar -xzf "${tmpdir}/conftest.tar.gz" -C "${tmpdir}" conftest
          install -m 0755 "${tmpdir}/conftest" "${TOOL_CACHE_DIR}/conftest/bin/conftest"
          rm -rf "${tmpdir}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Set up Flux CLI
        uses: fluxcd/flux2/action@v2
        with:
          version: '2.2.3'

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.3.0'

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: gitops-ci

      - name: Install Flux CRDs in kind cluster
        run: |
          set -euo pipefail
          flux install --components-extra=image-reflector-controller,image-automation-controller --export | kubectl apply -f -
          kubectl wait --for=condition=Available --timeout=120s -n flux-system deployments --all

      - name: Render manifests with Kustomize
        run: |
          set -euo pipefail
          mkdir -p rendered-manifests/kustomize
          mapfile -t kustomizations < <(find clusters k8s -name kustomization.yaml -print | sort)
          if [ "${#kustomizations[@]}" -eq 0 ]; then
            echo "No kustomization.yaml files found"
            exit 1
          fi
          for kustomization in "${kustomizations[@]}"; do
            dir=$(dirname "$kustomization")
            rel=${dir#./}
            safe_name=$(echo "$rel" | tr '/._' '-' | tr '[:upper:]' '[:lower:]')
            echo "Building ${rel}"
            kustomize build "$dir" > "rendered-manifests/kustomize/${safe_name}.yaml"
          done

      - name: Build manifests with Flux
        run: |
          set -euo pipefail
          mkdir -p rendered-manifests/flux
          mapfile -t kustomizations < <(find clusters k8s -name kustomization.yaml -print | sort)
          if [ "${#kustomizations[@]}" -eq 0 ]; then
            echo "No kustomization.yaml files found for Flux build"
            exit 0
          fi
          for kustomization in "${kustomizations[@]}"; do
            dir=$(dirname "$kustomization")
            rel=${dir#./}
            safe_name=$(echo "$rel" | tr '/._' '-' | tr '[:upper:]' '[:lower:]')
            tmp_file=$(mktemp)
            cat <<EOT > "$tmp_file"
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${safe_name}
  namespace: flux-system
spec:
  interval: 10m
  path: ./${rel}
  prune: false
  sourceRef:
    kind: GitRepository
    name: placeholder
EOT
            echo "Flux building ${rel}"
            flux build kustomization "${safe_name}" \
              --namespace=flux-system \
              --path=. \
              --kustomization-file="$tmp_file" \
              --dry-run > "rendered-manifests/flux/${safe_name}.yaml"
            rm -f "$tmp_file"
          done

      - name: Validate manifests with kubeconform
        run: |
          set -euo pipefail
          kubeconform -strict -ignore-missing-schemas -skip CustomResourceDefinition -summary rendered-manifests/kustomize/*.yaml

      - name: Server-side dry-run validation
        run: |
          set -euo pipefail
          python3 <<'PY'
import pathlib
import subprocess
import sys

import yaml

manifest_dir = pathlib.Path('rendered-manifests/kustomize')
failures = []
for manifest_file in sorted(manifest_dir.glob('*.yaml')):
    with manifest_file.open('r', encoding='utf-8') as fh:
        docs = list(yaml.safe_load_all(fh))
    for index, doc in enumerate(docs, start=1):
        if not doc:
            continue
        payload = yaml.safe_dump(doc, sort_keys=False).encode()
        proc = subprocess.run(
            ["kubectl", "apply", "--dry-run=server", "-f", "-"],
            input=payload,
            capture_output=True,
            check=False,
        )
        if proc.returncode != 0:
            stderr = proc.stderr.decode()
            if "no matches for kind" in stderr or "could not find the requested resource" in stderr:
                print(f"Skipping {manifest_file} document {index}: {stderr.strip()}")
                continue
            print(f"kubectl dry-run failed for {manifest_file} document {index}:\n{stderr}")
            failures.append((manifest_file, index, stderr))
if failures:
    sys.exit(1)
PY

      - name: Helm lint
        run: |
          set -euo pipefail
          mapfile -t charts < <(find . -name Chart.yaml -print | sort)
          if [ "${#charts[@]}" -eq 0 ]; then
            echo "No Helm charts found to lint"
            exit 0
          fi
          for chart_file in "${charts[@]}"; do
            chart_dir=$(dirname "$chart_file")
            echo "Linting Helm chart ${chart_dir}"
            helm lint "$chart_dir"
          done

      - name: Policy checks with Conftest
        run: |
          set -euo pipefail
          if [ -d policy ] || [ -d policies ]; then
            conftest test rendered-manifests/kustomize
          else
            echo "No policy directory found, skipping OPA/Conftest checks"
          fi

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered-manifests
          if-no-files-found: error
